set_property BITSTREAM.STARTUP.STARTUPCLK JTAGCLK [current_design]

set_property PACKAGE_PIN V14 [get_ports {reg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[7]}]
set_property PACKAGE_PIN U14 [get_ports {reg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[6]}]
set_property PACKAGE_PIN U15 [get_ports {reg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[5]}]
set_property PACKAGE_PIN W18 [get_ports {reg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[4]}]
set_property PACKAGE_PIN V19 [get_ports {reg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[3]}]
set_property PACKAGE_PIN U19 [get_ports {reg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[2]}]
set_property PACKAGE_PIN E19 [get_ports {reg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[1]}]
set_property PACKAGE_PIN U16 [get_ports {reg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[0]}]

set_property PACKAGE_PIN U18 [get_ports AC]
set_property IOSTANDARD LVCMOS33 [get_ports AC]
set_property PACKAGE_PIN W19 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports add]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN R2 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property PACKAGE_PIN T1 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN U1 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN W2 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]

set_property PACKAGE_PIN W17 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN W16 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN V16 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN V17 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]

set_property PACKAGE_PIN w5 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]